### ISSUE TITLE
can not see remove level safety button in revit 2022

### ISSUE THREAD

**Issue by bensaleden** [apex-project/pyApex#14]
![image](https://user-images.githubusercontent.com/127667549/224547588-719265d6-ab5c-4434-9419-20444c34a8d7.png)
![image](https://user-images.githubusercontent.com/127667549/224547609-342ffb47-3fdd-448f-9263-64e89fd37c1d.png)
![image](https://user-images.githubusercontent.com/127667549/224547632-56aa3df7-3595-460b-a611-a7353b7f0fd9.png)
![image](https://user-images.githubusercontent.com/127667549/224547659-14148957-289b-461e-82ec-acb0b96b7646.png)

**Comment by melnikovalex** [comment]
Hi @bensaleden 

So it looks like the script is currently hidden (marked as beta) and therefore is not visible by default. I will try to explain why it is so.

**You should use it on your risk.** It might not be completely "safe" since it hasn't been tested with all possible elements that could be affected by deleting a level.

However, if you want to check which elements will be deleted before deleting a level, you can use "Show dependent". And then decide on your own if a level deserves being deleteted. Keep in mind though, this feature also doesn't display all possible changes, like if you were to delete a level that walls are using as an upper dependency (the wall is won't be deleted but will lose an upper dependency)

If you want to show beta-scripts, you can enable the "Show Beta Scripts" checkbox in "pyRevit - Config - Development".

![image](https://user-images.githubusercontent.com/1159403/224665594-6c8d952a-3ce2-46bc-9ea2-1fefa18dca19.png)

Hopefully, this helps! If not, don't hesitate to reopen the issue.

Good luck with everything!
Alex
